# Generated by Django 5.1.6 on 2025-02-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('seller', 'Seller'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
