# Generated by Django 5.1.6 on 2025-02-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='address_field1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='address_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
