# Generated by Django 5.1.6 on 2025-03-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='Address',
            new_name='address',
        ),
    ]
