# Generated by Django 5.1.6 on 2025-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
