# Generated by Django 5.1.6 on 2025-03-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
