# Generated by Django 5.1.6 on 2025-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_cart_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
