# Generated by Django 5.1.6 on 2025-06-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_orderedproduct_price_at_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
