# Generated by Django 5.1.6 on 2025-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cart_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
