# Generated by Django 5.1.6 on 2025-06-04 00:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_remove_cart_coupon_id_cart_coupon_cart_discount'),
        ('users', '0009_notificationstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
