# Generated by Django 5.1.5 on 2025-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_alter_receiver_address_alter_receiver_email_and_more'),
        ('coupons', '0004_coupon_coupons_cou_code_3bf721_idx_and_more'),
        ('products', '0030_favouriteproduct_products_fa_user_id_14e965_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='carts_cart_session_e62e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_completed', 'date_completed'], name='carts_cart_is_comp_fb3f99_idx'),
        ),
        migrations.AddIndex(
            model_name='orderedproduct',
            index=models.Index(fields=['cart'], name='carts_order_cart_id_a00fac_idx'),
        ),
        migrations.AddIndex(
            model_name='orderedproduct',
            index=models.Index(fields=['product'], name='carts_order_product_56f8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='orderedproduct',
            index=models.Index(fields=['added_at'], name='carts_order_added_a_f0bb74_idx'),
        ),
    ]
