# Generated by Django 5.1.5 on 2025-09-18 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_one_time_per_user_coupon_usage_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('user', 'coupon'), name='unique_active_coupon'),
        ),
    ]
