# Generated by Django 5.1.5 on 2025-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_couponusage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_cou_code_3bf721_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['active', 'valid_from', 'valid_to'], name='coupons_cou_active_57a44c_idx'),
        ),
    ]
