# Generated by Django 5.1.5 on 2025-09-24 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_coupon_coupons_cou_code_3bf721_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon'),
        ),
    ]
