# Generated by Django 5.1.6 on 2025-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_module_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
