# Generated by Django 5.1.5 on 2025-09-23 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_module_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', 'created'], name='courses_cou_subject_7ff131_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['slug'], name='courses_sub_slug_dd8f7f_idx'),
        ),
    ]
