# Generated by Django 5.1.6 on 2025-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_brand_slug_characteristic_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
