# Generated by Django 5.1.6 on 2025-02-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_slug_alter_characteristic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
