# Generated by Django 5.1.6 on 2025-02-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_main_tag_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='main',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
