# Generated by Django 5.1.6 on 2025-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watched',
            field=models.IntegerField(default=0),
        ),
    ]
