# Generated by Django 5.1.6 on 2025-04-09 18:53

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_customtag_customtaggeditem_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='products.CustomTaggedItem', to='products.CustomTag', verbose_name='Tags'),
        ),
    ]
