# Generated by Django 5.1.6 on 2025-04-28 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_contact_subcription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcription',
            unique_together={('user', 'brand')},
        ),
        migrations.AddIndex(
            model_name='subcription',
            index=models.Index(fields=['user', 'brand'], name='products_su_user_id_d2d6ae_idx'),
        ),
    ]
