# Generated by Django 5.1.6 on 2025-05-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_subcription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcription',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='products.brand'),
        ),
    ]
