# Generated by Django 5.1.5 on 2025-09-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productactivationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productactivationrequest',
            name='comment',
        ),
    ]
