# Generated by Django 5.1.5 on 2025-09-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_productactivationrequest_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productactivationrequest',
            name='products_pr_product_7462d0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productactivationrequest',
            unique_together=set(),
        ),
    ]
