# Generated by Django 5.1.5 on 2025-09-16 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_productactivationrequest_products_pr_product_7462d0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='productcharacteristic',
            unique_together={('product', 'characteristic')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='products_br_slug_d4d839_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'quantity'], name='products_pr_is_acti_512b92_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='products_re_product_b03620_idx'),
        ),
    ]
