# Generated by Django 5.1.5 on 2025-09-23 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favouriteproduct',
            index=models.Index(fields=['user'], name='products_fa_user_id_14e965_idx'),
        ),
        migrations.AddIndex(
            model_name='favouriteproduct',
            index=models.Index(fields=['product'], name='products_fa_product_e1960b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='products_pr_brand_i_8f789e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='products_pr_product_3d7874_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='products_re_created_7e194a_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewimage',
            index=models.Index(fields=['review'], name='products_re_review__a7c535_idx'),
        ),
    ]
