# Generated by Django 5.1.5 on 2025-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_favouriteproduct_products_fa_user_id_14e965_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
